-- USE <your_db_in_application.properties>;

INSERT INTO `roles` VALUES
    (1,'ROL_CANDIDATO'),
    (2,'ROL_RECLUTADOR');

INSERT INTO `estados_republica` VALUES
    (1,'Aguascalientes'),
    (2,'Baja California'),
    (3,'Baja California Sur'),
    (9,'C.D.M.X.'),
    (4,'Campeche'),
    (5,'Chiapas'),
    (6,'Chihuahua'),
    (7,'Coahuila de Zaragoza'),
    (8,'Colima'),
    (10,'Durango'),
    (15,'Edo. de Mex.'),
    (11,'Guanajuato'),
    (12,'Guerrero'),
    (13,'Hidalgo'),
    (14,'Jalisco'),
    (16,'Michoacán de Ocampo'),
    (17,'Morelos'),
    (18,'Nayarit'),
    (19,'Nuevo León '),
    (20,'Oaxaca'),
    (21,'Puebla'),
    (22,'Querétaro'),
    (23,'Quintana Roo'),
    (24,'San Luis Potosí'),
    (25,'Sinaloa'),
    (26,'Sonora'),
    (27,'Tabasco'),
    (28,'Tamaulipas'),
    (29,'Tlaxcala'),
    (30,'Veracruz'),
    (31,'Yucatán'),
    (32,'Zacatecas');

INSERT INTO `estados_vacante` VALUES
    (5,'Contratado'),
    (2,'CV visto'),
    (3,'Entrevista'),
    (4,'Idóneo'),
    (1,'Postulado'),
    (6,'Rechazado');

INSERT INTO `idiomas` VALUES
    (1,'Alemán'),
    (2,'Árabe'),
    (3,'Armenio'),
    (4,'Bengalí'),
    (5,'Bielorruso'),
    (6,'Búlgaro'),
    (7,'Catalán'),
    (8,'Chino simplificado'),
    (9,'Chino tradicional'),
    (10,'Coreano'),
    (11,'Criollo haitiano'),
    (12,'Danés'),
    (13,'Eslovaco'),
    (14,'Esloveno'),
    (15,'Español'),
    (16,'Esperanto'),
    (17,'Finés'),
    (18,'Francés'),
    (19,'Gallego'),
    (20,'Hawaiano'),
    (21,'Hebreo'),
    (22,'Hindi'),
    (23,'Húngaro'),
    (24,'Indonesio'),
    (25,'Inglés'),
    (26,'Irlandés'),
    (27,'Italiano'),
    (28,'Japonés'),
    (29,'Latín'),
    (30,'Mongol'),
    (31,'Neerlandés'),
    (32,'Noruego'),
    (33,'Polaco'),
    (34,'Portugués'),
    (35,'Rumano'),
    (36,'Ruso'),
    (37,'Serbio'),
    (38,'Ucraniano'),
    (39,'Vietnamita');

INSERT INTO `universidades` VALUES
    (1,'Universidad de Guanajuato','UGTO',11),
    (2,'Benemerita Universidad Autónoma de Puebla','BUAP',21),
    (3,'Universidad Nacional Autónoma de México','UNAM',9),
    (4,'Instituo Politécnico Nacional','IPN',9),
    (5,'Universidad Veracruzana','UV',30),
    (6,'Universidad Autónoma de Nuevo León','UANL',19),
    (7,'Universidad Autónoma de Querétaro','UAQ',22),
    (8,'Universidad Autónoma del Estado de Morelos','UAEM',17),
    (9,'Universidad de Guadalajara','UDG',14),
    (10,'Tecnológico de Estudios Superiores Ecatepec','TESE',15),
    (11,'Universidad Pedagógica Nacional','UPN',9),
    (12,'Universidad Politécnica de Pachuca','UPP',13),
    (13,'Instituto Tecnológico de Oaxaca','ITO',20),
    (14,'Instituto tecnológico de Saltillo','ITS',7),
    (15,'Instituto Tecnológico Superior de Irapuato','ITESI',11),
    (16,'Instituto Tecnológico de Aguascalientes','ITA',1),
    (17,'Instituto Nacional de Bellas Artes y Literatura','INBAL',9),
    (18,'Escuela de la Salud Pública','ESPM',9),
    (19,'Centro de Investigaciones y Docencia Económicas','CIDE',9),
    (20,'Centro de Capacitación Cinematográfica','CCC',9),
    (21,'Universidad de Sonora','UNISON',26),
    (22,'Universidad Tencológica de Tijuana','UTT',2),
    (23,'Instituto Tecnológico de Morelia','ITM',16),
    (24,'Universidad de Quintana Roo','UQROO',23),
    (25,'Centro de Investigaciones Biológicas del Noroeste','CIBNOR',3),
    (26,'Instituto Tecnológico de Lerma','TECNML',4);

INSERT INTO `puestos` VALUES
    (1,'Reclutador'),
    (2,'Reclutador Principal'),
    (3,'Reclutador (Industria de la Salud)'),
    (4,'Especialista en Recursos Humanos'),
    (5,'Especialista en abastecimiento para Recursos Humanos'),
    (6,'Reclutador técnico');

INSERT INTO `beneficios`(nombre)  VALUES
    ('Aportación de la empresa al plan de pensiones'),
    ('Planes de pago de préstamos para estudiantes'),
    ('Descuentos en viajes + viajes compartidos'),
    ('Coche de empresa'),
    ('Planes de teléfonos móviles con descuento para familiares'),
    ('Reembolso de matrícula'),
    ('Fondo de desarrollo profesional'),
    ('Alojamiento totalmente gratuito'),
    ('Seguro de mascotas'),
    ('Reembolso por servicio de guardería'),
    ('Remuneración en educación y cuidado infantil'),
    ('Tickets para restaurantes'),
    ('Tarjeta de retribución flexible'),
    ('Catálogo de premios para empleados'),
    ('Programa de recomendación de empleados'),
    ('Programa de educación financiera'),
    ('Programa de ahorro para empleados'),
    ('Reembolso en productos/servicios de tecnología'),
    ('Programas de inversión'),
    ('Reembolso de combustible'),
    ('Espacio de estacionamiento gratuito'),
    ('Servicio de limpieza de coches gratuita'),
    ('Suscripción de pañales + toallitas'),
    ('Ayuda para comprar una casa'),
    ('Campamento de verano para los hijos de los empleados'),
    ('Planificación de la jubilación'),
    ('Congelación de óvulos'),
    ('Fondo para nacimientos'),
    ('Accesorios de vestimenta'),
    ('Bienestar físico y mental'),
    ('Clases y actividades variadas'),
    ('Reembolso de bienestar'),
    ('Gimnasio en la oficina'),
    ('Centro de salud y bienestar a su alcance'),
    ('Vacunas contra la gripe gratuitas'),
    ('Espacios de trabajo con cintas de correr'),
    ('Plan de reembolso de fitness'),
    ('Protectores de pantalla'),
    ('Beneficios de atención médica inclusivos para personas transexuales'),
    ('Cupones de descuento para fisioterapia, osteopatía y quiromasaje'),
    ('Subvención para tratamiento de fertilidad in vitro'),
    ('Salas de lactancia con atención médica'),
    ('Análisis regulares'),
    ('Servicios de atención a personas mayores'),
    ('Beneficios para formar una familia'),
    ('Programa de caminar hacia trabajo'),
    ('Estacionamiento designado para mujeres embarazadas'),
    ('Masajes en la oficina'),
    ('Bienestar emocional'),
    ('Días de permiso adicionales por fallecimiento de un familiar'),
    ('Talleres de salud mental y manejo del estrés'),
    ('Suscripciones gratuitas a aplicaciones de salud mental'),
    ('App/Instalaciones de Mindfulness'),
    ('Programas de Asistencia al Empleado (PAE)'),
    ('Cápsulas de sueño en la oficina'),
    ('Días de salud mental'),
    ('Días para “salir de la zona de confort”'),
    ('Programa de trabajo remoto'),
    ('Descuentos para viajar'),
    ('Permiso de cuidados para mascotas'),
    ('Guardería en la oficina'),
    ('Ayuda y asistencia para adopción'),
    ('Acompañante de viaje para las nuevas madres'),
    ('Envío de leche materna de cortesía'),
    ('Programas para volver a la a la rutina laboral'),
    ('Asistencia para la reasignación de género'),
    ('Bienestar social'),
    ('Ticket o tarjeta cultural'),
    ('Invitaciones a ases privados de películas'),
    ('Club de lectura'),
    ('Programa de tutoría/mentoría interno'),
    ('Certificados/Títulos específicos'),
    ('Curso de prejuicios + diversidad'),
    ('Programa de coach universitario'),
    ('Formación sobre conciencia LGBT'),
    ('Donaciones caritativas'),
    ('Oportunidades de voluntariado en la oficina'),
    ('Oportunidades de voluntariado fuera de la oficina'),
    ('Días de vacaciones extra para obras de caridad'),
    ('Actividades mensuales del equipo'),
    ('Vacaciones ilimitadas'),
    ('Viernes de teletrabajo'),
    ('Charlas a la hora del almuerzo'),
    ('Viernes de verano – media jornada'),
    ('Día libre de cumpleaños'),
    ('Periodos sabáticos remunerados'),
    ('Horario flexible y libre'),
    ('Semana laboral de 4 días'),
    ('Programa de media jornada para padres'),
    ('Código de vestimenta “casual”'),
    ('Programa de “implant”'),
    ('Salas de juego'),
    ('Reuniones de equipos externos'),
    ('Día de disfraces'),
    ('Día de “bienvenidas mascotas”'),
    ('Intercambio con otros equipos'),
    ('Día de “bienvenida familia”'),
    ('Fiestas para niños'),
    ('Barista o cafetería en la oficina'),
    ('Platos preparados y refrigerios'),
    ('Bebidas gratis después de las 18 horas'),
    ('Entrega de comida gratis'),
    ('Entrega de compras o pedidos');
